FROM jenkins/jenkins:lts

USER root

# Force IPv4 + reliable apt
RUN apt-get update -o Acquire::ForceIPv4=true && \
    apt-get install -y --no-install-recommends \
        docker.io \
        make \
        g++ \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker jenkins

USER jenkins
